version: '3.5'

services:
  redis:
    container_name: redis
    image: redis

  ui:
    container_name: ui
    image: borysekondrej/bakalarka-frontend
    env_file:
      - frontend/.env

  flask:
    container_name: flask
    image: borysekondrej/bakalarka-backend
    depends_on:
      - redis
    volumes:
      - db:/app/bakalarka3/db
      - flask-logs:/app/bakalarka3/log
    env_file:
      - backend/.env      

  sslyze_scanner_new:
    container_name: sslyze_scanner_new
    image: borysekondrej/bakalarka-backend
    depends_on:
      - redis
      - flask
    env_file:
      - backend/.env      
  
  # sslyze_scanner_recurring:
  #   container_name: sslyze_scanner_recurring
  #   image: borysekondrej/bakalarka-backend
  #   depends_on:
  #     - redis
  #     - flask
  #   env_file:
  #     - sslyze_rq/.env      

  nginx:
    container_name: nginx
    build: nginx
    depends_on:
      - ui
      - flask
    ports:
      - "443:443"

  sqlite-web:
    container_name: sqlite-web
    image: coleifer/sqlite-web
    volumes:
      - db:/app/bakalarka3/db
    environment:
      - SQLITE_DATABASE=test.db
    ports:
      - "5001:8080"

volumes:
  db:
  flask-logs:
